/* =====================================================================
   print-css.mjs — generate the print overlay CSS from a config object.
   ---------------------------------------------------------------------
   The overlay supplies the two things a screen-designed HTML page almost
   always lacks when you want a print PDF:

     1. Page numbers (folios), optionally suppressed on a cover page.
     2. Live table-of-contents page references via target-counter().

   It also adds defensive pagination rules (keep-together / no orphaned
   headings) so the rendered PDF doesn't strand titles or split figures.

   The output is injected into the source HTML before rendering with
   Paged.js (headless Chrome). Nothing here touches the document's own
   visual design — it only adds print semantics on top.

   NOTE on Paged.js quirks baked into this generator:
     - Paged.js cannot resolve CSS custom properties (var()) inside @page
       rules, so page geometry is written with literal values.
     - Its selector rewriter is fragile with combined :first-of-type / "+"
       selectors, so the defensive rules are kept simple and standalone.
   ===================================================================== */

export const DEFAULT_CONFIG = {
  // Page geometry
  size: "A4",                 // "A4", "Letter", "6in 9in", "210mm 297mm", ...
  margin: "18mm",             // any CSS margin shorthand

  // Page numbers (folios)
  pageNumbers: true,
  pageNumberPosition: "bottom-center", // bottom-center | bottom-left | bottom-right
  pageNumberColor: "#444444",
  pageNumberFont: "sans-serif",
  pageNumberFontSize: "9pt",

  // Cover: gets its own page with no folio. Set to null to disable.
  coverSelector: ".cover",

  // Optional: element where the visible page count restarts at 1
  // (e.g. an imprint/copyright page, so the cover isn't counted).
  startCounterSelector: null,

  // Table of contents: links matching this selector get a live page number
  // appended after layout. Set to null to disable.
  tocLinkSelector: '.toc a[href^="#"]',
  tocNumberColor: "#444444",

  // Defensive pagination (keep-together / no orphaned headings).
  paginationSafety: true,
};

const POSITION_SLOT = {
  "bottom-center": "@bottom-center",
  "bottom-left": "@bottom-left",
  "bottom-right": "@bottom-right",
};

export function buildPrintCSS(userConfig = {}) {
  const c = { ...DEFAULT_CONFIG, ...userConfig };
  const slot = POSITION_SLOT[c.pageNumberPosition] || "@bottom-center";
  const out = [];

  out.push(`/* print overlay — generated by html-to-print-pdf */`);

  /* ---- page geometry ---- */
  out.push(`@page {`);
  out.push(`  size: ${c.size};`);
  out.push(`  margin: ${c.margin};`);
  if (c.pageNumbers) {
    out.push(`  ${slot} {`);
    out.push(`    content: counter(page);`);
    out.push(`    font-family: ${c.pageNumberFont};`);
    out.push(`    font-size: ${c.pageNumberFontSize};`);
    out.push(`    color: ${c.pageNumberColor};`);
    out.push(`  }`);
  }
  out.push(`}`);

  /* ---- cover: own page, no folio, full bleed (margin removed) ---- */
  if (c.coverSelector) {
    out.push(`${c.coverSelector} { page: cover; break-after: page; }`);
    out.push(`@page cover { margin: 0; ${slot} { content: none; } }`);
  }

  /* ---- restart visible page count ---- */
  if (c.startCounterSelector) {
    out.push(`${c.startCounterSelector} { counter-reset: page 1; }`);
  }

  /* ---- live TOC page references ---- */
  if (c.tocLinkSelector) {
    out.push(`${c.tocLinkSelector}::after {`);
    out.push(`  content: target-counter(attr(href), page);`);
    out.push(`  margin-left: 12px;`);
    out.push(`  color: ${c.tocNumberColor};`);
    out.push(`  font-variant-numeric: tabular-nums;`);
    out.push(`  white-space: nowrap;`);
    out.push(`}`);
  }

  /* ---- defensive pagination ---- */
  if (c.paginationSafety) {
    out.push(`/* keep headings with the content they introduce */`);
    out.push(`h1, h2, h3, h4, h5, h6 { break-after: avoid; }`);
    out.push(`/* don't split atomic blocks across pages */`);
    out.push(`figure, table, pre, blockquote { break-inside: avoid; }`);
    out.push(`tr, li { break-inside: avoid; }`);
    out.push(`img { max-width: 100%; }`);
    out.push(`p { widows: 2; orphans: 2; }`);
  }

  return out.join("\n") + "\n";
}
